name: cyber_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login/images/group-user-1.png
    - assets/login/images/user-1-1.png
    - assets/login/images/book-1.png
    - assets/login/images/bank-1.png
    - assets/login/images/icon-youtube-1.png
    - assets/login/images/user-1-1-169.png
    - assets/login/images/logo-fb-1.png
    - assets/login/images/logo-line-1.png
    - assets/login/images/global-1.png
    - assets/login/images/bank-1-qrR.png
    - assets/login/images/bank-1-7SZ.png
    - assets/login/images/user-1-1-jw7.png
    - assets/login/images/group-user-1-fZs.png
    - assets/login/images/group-user-1-Hi9.png
    - assets/login/images/user-1-1-wmK.png
    - assets/login/images/user-2-1.png
    - assets/login/images/icon-notification3-1.png
    - assets/login/images/icon-notification3-1-DMb.png
    - assets/login/images/user-2-1-xpy.png
    - assets/login/images/eye-1.png
    - assets/login/images/book-1-xFj.png
    - assets/login/images/instagram-1.png
    - assets/login/images/icon-notification3-1-CrD.png
    - assets/login/images/user-1-1-MDK.png
    - assets/login/images/icon-notification3-1-h2H.png
    - assets/login/images/polygon-2.png
    - assets/login/images/user-2-1-NGZ.png
    - assets/login/images/facebook-1.png
    - assets/login/images/monitoritc-1.png
    - assets/login/images/bank-1-xVf.png
    - assets/login/images/book-1-wbX.png
    - assets/login/images/monitoritc-1-V7F.png
    - assets/login/images/instagram-icon-2.png
    - assets/login/images/group-user-1-zXb.png
    - assets/login/images/bank-1-oHB.png
    - assets/login/images/youtube-1.png
    - assets/login/images/logo-line-1-JDw.png
    - assets/login/images/polygon-1.png
    - assets/login/images/footer.png
    - assets/login/images/image-1.png
    - assets/login/images/footer-oYD.png
    - assets/login/images/polygon-2-95b.png
    - assets/login/images/ellipse-1.png
    - assets/login/images/logo-line-1-FX7.png
    - assets/login/images/monitoritc-1-hEq.png
    - assets/login/images/logo-line-1-Dys.png
    - assets/login/images/logo-line-1-nXB.png
    - assets/login/images/union.png
    - assets/login/images/user-1-1-jZT.png
    - assets/login/images/icon-notification3-1-57X.png
    - assets/login/images/instagram-icon-1.png
    - assets/login/images/back.png
    - assets/login/images/setting-1.png
    - assets/login/images/logo-line-1-znm.png
    - assets/login/images/user-2-1-iim.png
    - assets/login/images/book-1-ifT.png
    - assets/login/images/instagram-icon-2-qVB.png
    - assets/login/images/user-1-1-B3F.png
    - assets/login/images/monitoritc-1-jaZ.png
    - assets/login/images/group-13.png
    - assets/login/images/footer-iQ1.png
    - assets/login/images/logo-fb-1-Et9.png
    - assets/login/images/footer-C4H.png
    - assets/login/images/footer-MSy.png
    - assets/login/images/footer-7h3.png
    - assets/login/images/book-1-6iD.png
    - assets/login/images/group-user-1-2rm.png
    - assets/login/images/icon-youtube-1-yX7.png
    - assets/login/images/tabel.png
    - assets/login/images/footer-iDo.png
    - assets/login/images/monitoritc-1-feq.png
    - assets/login/images/user-2-1-2kH.png
    - assets/login/images/polygon-2-nDf.png
    - assets/login/images/footer-FvR.png
    - assets/login/images/footer-9AZ.png
    - assets/login/images/footer-r1f.png
    - assets/login/images/logo-line-1-y6H.png
    - assets/login/images/footer-oMj.png
    - assets/login/images/monitoritc-1-L6m.png
    - assets/login/images/monitoritc-1-HXo.png
    - assets/login/images/monitoritc-1-R8d.png
    - assets/login/images/monitoritc-1-6m7.png
    - assets/login/images/logo-line-1-KC5.png
    - assets/login/images/logo-line-1-EK3.png
    - assets/login/images/instagram-icon-1-z8H.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
